# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "simple_config"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fallwith"]
  s.date = "2013-03-13"
  s.description = "For demonstration purposes only, SimpleConfig demonstrates Ruby code"
  s.email = "fallwith"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.homepage = "http://github.com/fallwith/simple_config"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "SimpleConfig - a simple key/val config file parser"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, ["= 2.13.0"])
      s.add_runtime_dependency(%q<jeweler>, ["= 1.8.4"])
      s.add_runtime_dependency(%q<yard>, ["= 0.8.5.2"])
    else
      s.add_dependency(%q<rspec>, ["= 2.13.0"])
      s.add_dependency(%q<jeweler>, ["= 1.8.4"])
      s.add_dependency(%q<yard>, ["= 0.8.5.2"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 2.13.0"])
    s.add_dependency(%q<jeweler>, ["= 1.8.4"])
    s.add_dependency(%q<yard>, ["= 0.8.5.2"])
  end
end

